# Generated by Django 2.2 on 2021-11-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regi',
            name='email',
            field=models.TextField(max_length=100),
        ),
    ]
