# Generated by Django 2.2 on 2021-11-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211126_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regi',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
