# Generated by Django 2.2 on 2021-11-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211126_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regi',
            name='email',
        ),
    ]
