# Generated by Django 2.2 on 2021-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_regi_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regi',
            name='password2',
        ),
        migrations.AddField(
            model_name='regi',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
