# Generated by Django 2.2 on 2021-11-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211127_0602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regi',
        ),
    ]
